version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: bot_valley_production_django
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
      - ./.envs/.production/.telegram
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: bot_valley_production_postgres
    restart: always
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  telegram_bot:
    <<: *django
    image: bot_valley_production_telegram_bot
    restart: always
    depends_on:
      - django
    ports:
      - "5000:5000"
    command: python start_bot.py

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: bot_valley_production_traefik
    restart: always
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:5.0
    restart: always
