# Generated by Django 3.1.13 on 2021-07-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0004_alter_options_ordering_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sites', models.ManyToManyField(blank=True, to='sites.Site')),
            ],
        ),
    ]
