# Generated by Django 3.1.13 on 2021-07-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Telegram bot user', 'verbose_name_plural': 'Telegram bot users'},
        ),
    ]
